"""Stabilne identyfikatory i stałe pierwszej wersji."""

RULE_NO_GUESSING = "REQ-NO-GUESSING-001"
RULE_SPECIAL_DAY = "REQ-SPECIAL-DAY-001"
RULE_TIME_STEP = "REQ-TIME-STEP-001"
RULE_SAME_DAY = "REQ-TIME-SAME-DAY-001"
RULE_SEGMENT_MIN = "REQ-SEGMENT-MIN-001"
RULE_COVERAGE = "REQ-COVERAGE-001"
RULE_STAFFING = "REQ-STAFFING-001"
RULE_NO_OUTSIDE = "REQ-NO-OUTSIDE-001"
RULE_HOURS = "REQ-HOURS-001"
RULE_DAYS = "REQ-DAYS-001"
RULE_HARD_UNAVAILABLE = "REQ-UNAVAILABLE-HARD-001"
RULE_REST_DAILY = "REQ-REST-DAILY-001"
RULE_REST_WEEKLY = "REQ-REST-WEEKLY-001"
RULE_WEEKEND = "REQ-WEEKEND-001"
RULE_ROTATION = "REQ-ROTATION-001"
RULE_CROSS_WEEK = "REQ-CROSS-WEEK-001"
RULE_VALIDATOR_INDEPENDENT = "REQ-VALIDATOR-INDEP-001"
RULE_LEGAL = "REQ-LEGAL-001"

RULE_PREF_AFTERNOON = "REQ-PREF-AFTERNOON-001"
RULE_PREF_WEEKEND = "REQ-PREF-WEEKEND-SPLIT-001"
RULE_PREF_SPLIT = "REQ-PREF-SPLIT-DAYS-001"
RULE_PREF_LONG = "REQ-PREF-LONG-SEGMENT-001"
RULE_PREF_UNAVAILABLE = "REQ-PREF-UNAVAILABLE-001"

TIME_STEP_MINUTES = 30
MINIMUM_SEGMENT_MINUTES = 120
REQUIRED_WORK_DAYS = 5
CYCLE_WEEKS = 6
CYCLE_DAYS = 42
SLOTS_PER_DAY = 48

CRITICAL_RULES = (
    RULE_NO_GUESSING,
    RULE_SPECIAL_DAY,
    RULE_TIME_STEP,
    RULE_SAME_DAY,
    RULE_SEGMENT_MIN,
    RULE_COVERAGE,
    RULE_STAFFING,
    RULE_NO_OUTSIDE,
    RULE_HOURS,
    RULE_DAYS,
    RULE_HARD_UNAVAILABLE,
    RULE_REST_DAILY,
    RULE_REST_WEEKLY,
    RULE_WEEKEND,
    RULE_ROTATION,
    RULE_CROSS_WEEK,
    RULE_VALIDATOR_INDEPENDENT,
    RULE_LEGAL,
)
