import type { ScheduleConfiguration } from "../types";

export const configurationFixture: ScheduleConfiguration = {
  schemaVersion: 2,
  projectId: "TEST",
  projectName: "Testowy harmonogram",
  configurationVersionId: "CV-TEST",
  versionNumber: 1,
  groupId: "G1",
  groupName: "Grupa testowa",
  cycleStartDate: "2026-09-14",
  weekStartDay: "MONDAY",
  timeZoneId: "Europe/Warsaw",
  educatorCount: 3,
  planningHorizonWeeks: 1,
  scheduleBoundaryMode: "FINITE",
  startingWeekendVariant: 1,
  requestedOperationMode: "DEMONSTRATION",
  educators: ["A", "B", "C"].map((id, index) => ({
    id,
    groupId: "G1",
    displayName: `Wychowawca ${id}`,
    shortCode: id,
    baseWeeklyAssignedMinutes: index === 2 ? 1620 : 1650,
    description: "",
    active: true,
    canWorkWeekends: true,
  })),
  assignmentOverrides: [],
  dayPlans: [],
  unavailability: [],
  legalRules: {
    id: "LEGAL",
    configurationVersionId: "CV-TEST",
    jurisdiction: "PL",
    sourceTitle: "Profil demonstracyjny",
    sourceSection: "test",
    sourceIdentifier: "test",
    version: "demo-1",
    verificationNotes: "Dane testowe.",
    verificationStatus: "UNVERIFIED",
    minimumDailyRestMinutes: 660,
    weeklyRestWindowType: "FIXED_LOCAL_WEEK",
    weeklyRestWindowLengthMinutes: 10080,
    weeklyRestWindowStepMinutes: 10080,
    weeklyRestAnchorDayOfWeek: 0,
    weeklyRestAnchorTime: "00:00",
    minimumWeeklyRestMinutes: 2100,
    weeklyRestAttributionMode: "INTERSECTION_WITH_WINDOW",
    weeklyRestReuseAcrossWindowsAllowed: true,
    weeklyRestExceptionEnabled: false,
    weeklyRestCompensationRequired: false,
  },
  organizationalRules: {
    id: "ORG",
    configurationVersionId: "CV-TEST",
    timeStepMinutes: 30,
    minimumSegmentMinutes: 120,
    requiredWorkDaysPerWeek: 5,
    weekendRotationEnabled: true,
    preferredMaximumSegmentMinutes: 480,
    preferredAfternoonHandoverTime: "17:00",
    preferredWeekendSplitMinutes: 480,
    splitDayPenaltyWeight: 1,
    preferredUnavailabilityPenaltyWeight: 1,
    longSegmentPenaltyWeight: 1,
    weekendImbalancePenaltyWeight: 1,
    afternoonHandoverPenaltyWeight: 1,
  },
  weekendVariants: [],
  solverTimeLimitSeconds: 20,
  randomSeed: 1,
  demonstrationNotice: "Tylko demonstracja.",
};
